# Generated by Django 4.1.2 on 2022-11-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theboxapp', '0002_alter_donatedmealswipe_receivedby_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutritionFacts', models.TextField(blank=True)),
                ('receivedBy', models.TextField(blank=True)),
                ('creationTime', models.DateTimeField(auto_now_add=True)),
                ('receivedTime', models.DateTimeField(blank=True, null=True)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
