# Generated by Django 4.1.2 on 2022-11-23 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theboxapp', '0003_thebox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donatedmealswipe',
            name='donatedBy',
        ),
        migrations.RemoveField(
            model_name='donatedmealswipe',
            name='receivedBy',
        ),
        migrations.RemoveField(
            model_name='thebox',
            name='receivedBy',
        ),
        migrations.AddField(
            model_name='donatedmealswipe',
            name='receiveUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiveUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thebox',
            name='receiveUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donatedmealswipe',
            name='donateUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donateUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
