# Generated by Django 4.1.2 on 2022-12-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theboxapp', '0006_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
