# Generated by Django 4.1.2 on 2022-12-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theboxapp', '0009_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
